// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdpcE2hnGR1EnuQ1xNpcbecYNk6YcEU2Q',
    appId: '1:728611566746:web:f3bcacec11e82f38e75b23',
    messagingSenderId: '728611566746',
    projectId: 'mytodo-5197d',
    authDomain: 'mytodo-5197d.firebaseapp.com',
    storageBucket: 'mytodo-5197d.appspot.com',
    measurementId: 'G-J10ZVMFRKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLDA3fLNZjTunmFJqMde6rEXfbFMufeMY',
    appId: '1:728611566746:android:810066e3c179bd62e75b23',
    messagingSenderId: '728611566746',
    projectId: 'mytodo-5197d',
    storageBucket: 'mytodo-5197d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN8aYnIxt8IBNKb2xHiylkIJ9LGpVUv04',
    appId: '1:728611566746:ios:1c3d0777f4ac60e4e75b23',
    messagingSenderId: '728611566746',
    projectId: 'mytodo-5197d',
    storageBucket: 'mytodo-5197d.appspot.com',
    iosClientId: '728611566746-020pcatd004jafi3eohshods97pbip44.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN8aYnIxt8IBNKb2xHiylkIJ9LGpVUv04',
    appId: '1:728611566746:ios:1c3d0777f4ac60e4e75b23',
    messagingSenderId: '728611566746',
    projectId: 'mytodo-5197d',
    storageBucket: 'mytodo-5197d.appspot.com',
    iosClientId: '728611566746-020pcatd004jafi3eohshods97pbip44.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytodo',
  );
}
